# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('path_hash', models.CharField(blank=True, max_length=255)),
                ('icon', models.CharField(blank=True, choices=[('logo', 'Logo'), ('skills', 'Spanner and Screwdriver'), ('projects', '@ symbol'), ('demos', 'Laboratory Beaker')], max_length=200)),
                ('background', models.CharField(blank=True, choices=[('/static/backgrounds/asanoha-400px.png', 'Japanese Asanoha'), ('/static/backgrounds/triangles.png', 'Triangles and Hexagons'), ('/static/backgrounds/pyramids.png', 'Pyramids'), ('/static/backgrounds/seigaiha.png', 'Seigaiha'), ('/static/backgrounds/squares.png', 'Grey and White Squares')], max_length=200)),
                ('text_colour', models.CharField(blank=True, choices=[('light', 'Light Text'), ('dark', 'Dark Text')], max_length=200)),
                ('title', models.CharField(max_length=20)),
                ('display_title', models.CharField(blank=True, max_length=255)),
                ('intro_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='childregion',
            name='parent_region',
        ),
        migrations.AlterModelOptions(
            name='primaryregion',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='primaryregion',
            name='background',
            field=models.CharField(blank=True, choices=[('/static/backgrounds/asanoha-400px.png', 'Japanese Asanoha'), ('/static/backgrounds/triangles.png', 'Triangles and Hexagons'), ('/static/backgrounds/pyramids.png', 'Pyramids'), ('/static/backgrounds/seigaiha.png', 'Seigaiha'), ('/static/backgrounds/squares.png', 'Grey and White Squares')], max_length=200),
        ),
        migrations.AlterField(
            model_name='primaryregion',
            name='icon',
            field=models.CharField(blank=True, choices=[('logo', 'Logo'), ('skills', 'Spanner and Screwdriver'), ('projects', '@ symbol'), ('demos', 'Laboratory Beaker')], max_length=200),
        ),
        migrations.AlterField(
            model_name='primaryregion',
            name='text_colour',
            field=models.CharField(blank=True, choices=[('light', 'Light Text'), ('dark', 'Dark Text')], max_length=200),
        ),
        migrations.DeleteModel(
            name='ChildRegion',
        ),
        migrations.AddField(
            model_name='subregion',
            name='parent_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.PrimaryRegion'),
        ),
    ]
