# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20170824_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('module_type', models.CharField(choices=[('text', 'Text'), ('skills_accordion', 'Skills Accordion'), ('demos_menu', 'Demos Menu')], max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.SubRegion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
