# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_auto_20170906_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodule',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.SubRegion'),
        ),
        migrations.AlterField(
            model_name='primaryregion',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
