# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-06 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_auto_20170906_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subregion',
            name='parent_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.PrimaryRegion', to_field='title'),
        ),
    ]
