# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='icon',
            field=models.CharField(blank=True, choices=[('logo', 'Logo'), ('skills', 'Spanner and Screwdriver'), ('projects', '@ symbol'), ('demos', 'Laboratory Beaker')], max_length=200),
        ),
    ]
