# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='target',
            field=models.CharField(choices=[('/skills/', 'Skills'), ('/demos/', 'Demos'), ('/projects/', 'Projects')], max_length=50),
        ),
    ]
