# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170802_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='target',
            field=models.CharField(choices=[('Enter path hash', 'Joseph Falconer | Web Developer'), ('Enter path hash', 'Skills'), ('Enter path hash', 'Demos'), ('Enter path hash', 'Projects'), ('Enter path hash', 'About'), ('Enter path hash', 'Multidisciplinary Developer'), ('Enter path hash', 'Letting creativity run things'), ('Enter path hash', 'Putting the skills to service')], max_length=50),
        ),
    ]
