# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170905_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='linked_region',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('toolkit', 'Toolkit'), ('demos', 'Demos'), ('projects', 'Projects')], default=None, max_length=50),
        ),
    ]
