# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170802_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigationlink',
            old_name='target',
            new_name='linked_region',
        ),
    ]
