# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170802_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='linked_region',
            field=models.CharField(choices=[('/', 'Joseph Falconer | Web Developer'), ('skills', 'Skills'), ('demos', 'Demos'), ('projects', 'Projects'), ('about', 'About'), ('skills-read', 'Multidisciplinary Developer'), ('demo-examples', 'Letting creativity run things'), ('live-projects', 'Putting the skills to service')], max_length=50),
        ),
    ]
