# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_delete_navigationlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=25)),
                ('linked_region', models.CharField(choices=[('', 'Joseph Falconer | Web Developer'), ('skills', 'Skills'), ('demos', 'Demos'), ('projects', 'Projects'), ('about', 'About'), ('skills-read', 'Multidisciplinary Developer'), ('demo-example', 'Letting creativity run things'), ('live-projects', 'Putting the skills to service')], max_length=50)),
            ],
        ),
    ]
