# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 23:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170803_0017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationLink',
        ),
    ]
