# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_navigationlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='linked_region',
            field=models.CharField(blank=True, choices=[('start', 'Joseph Falconer | Web Developer'), ('skills', 'Skills'), ('demos', 'Demos'), ('projects', 'Projects'), ('about', 'About'), ('skills-read', 'Multidisciplinary Developer'), ('demo-example', 'Letting creativity run things'), ('live-projects', 'Putting the skills to service')], default=None, max_length=50),
        ),
    ]
