# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170807_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='text',
            field=models.CharField(choices=[('Start', 'Start'), ('Skills', 'Skills'), ('Demos', 'Demos'), ('Projects', 'Projects'), ('About', 'About'), ('Read skills', 'Read skills'), ('See demos', 'See demos'), ('See projects', 'See projects')], max_length=20),
        ),
    ]
