# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20170807_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationlink',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='navigationlink',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='linked_region',
            field=models.CharField(blank=True, choices=[('', 'Start'), ('skills', 'Skills'), ('demos', 'Demos'), ('projects', 'Projects'), ('about', 'About'), ('skills-read', 'Read skills'), ('demo-example', 'See demos'), ('live-projects', 'See projects')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='navigationlink',
            name='text',
            field=models.CharField(max_length=20),
        ),
    ]
