# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20170809_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='linked_region',
            field=models.CharField(blank=True, choices=[('', 'Start'), ('skills', 'Skills'), ('demos', 'Demos'), ('projects', 'Projects'), ('about', 'About'), ('skills-areas', 'Read skills'), ('demo-example', 'See demos'), ('live-projects', 'See projects')], default=None, max_length=50),
        ),
    ]
