# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage', to='pages.Page')),
            ],
            options={
                'verbose_name_plural': 'Homepage',
            },
        ),
    ]
