# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodule',
            name='module_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('TOOLS_ACCORDION', 'Tools Accordion'), ('DEMOS_MENU', 'Demos Menu')], max_length=100),
        ),
    ]
