# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-23 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181008_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='page',
        ),
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
