# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-02-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_is_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_pages', to='pages.Page'),
        ),
    ]
