# Generated by Django 2.1.7 on 2019-02-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190218_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='background',
            field=models.CharField(blank=True, choices=[('/static/images/asanoha-400px.png', 'Japanese Asanoha'), ('/static/images/triangles.png', 'Triangles and Hexagons'), ('/static/images/pyramids.png', 'Pyramids'), ('/static/images/seigaiha.png', 'Seigaiha'), ('/static/images/squares.png', 'Grey and White Squares')], max_length=200),
        ),
    ]
