# Generated by Django 2.1.7 on 2019-02-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190218_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_pages', to='pages.Page'),
        ),
    ]
