# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-06 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200511_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='text_colour',
        ),
        migrations.AddField(
            model_name='page',
            name='theme',
            field=models.CharField(choices=[(b'LIGHT', b'Light'), (b'DARK', b'Dark')], default=b'LIGHT', max_length=200),
        ),
    ]
