backup_dict = {
	'primary_regions': [
		{'id': 1, 'created_at': datetime.datetime(2017, 8, 24, 16, 15, 30, 797597, tzinfo=<UTC>), 'order': 0, 'path_hash': 'start', 'icon': 'logo', 'background': '/static/backgrounds/asanoha-400px.png', 'text_colour': 'light', 'title': 'Start', 'display_title': 'Welcome!', 'intro_text': "Hi there. I'm Joseph Falconer and you're visiting my single-page application. These 'page' views are generated with client-side JavaScript rather than traditional web pages. Please have a click around and enjoy!", 'center_content': True}, 
		{'id': 2, 'created_at': datetime.datetime(2017, 8, 24, 16, 17, 21, 845855, tzinfo=<UTC>), 'order': 1, 'path_hash': 'toolkit', 'icon': 'skills', 'background': '/static/backgrounds/triangles.png', 'text_colour': 'light', 'title': 'Toolkit', 'display_title': '', 'intro_text': 'Modern web development offers a vast abundance of tools - most projects require a combination of at least several of them. That makes a multi-disciplinary approach the natural course to me. Well-integrated digital ecosystems are my day-to-day environment.', 'center_content': True}, 
		{'id': 3, 'created_at': datetime.datetime(2017, 8, 24, 16, 17, 46, 699104, tzinfo=<UTC>), 'order': 2, 'path_hash': 'experiments', 'icon': 'demos', 'background': '/static/backgrounds/pyramids.png', 'text_colour': 'light', 'title': 'Experiments', 'display_title': 'Fun Experiments', 'intro_text': 'I love a side project which explores the range of what my tools can do. The inventive process of re-synthesising ideas and adding new angles is hugely rewarding and helps to motivate my day-to-day practice.', 'center_content': True}
	], 
	'sub_regions': [
		{'id': 2, 'created_at': datetime.datetime(2017, 8, 24, 22, 49, 45, 904507, tzinfo=<UTC>), 'order': 0, 'path_hash': 'about', 'icon': '', 'background': '/static/backgrounds/squares.png', 'text_colour': 'dark', 'title': 'About', 'display_title': '', 'intro_text': '', 'center_content': False, 'parent_region': <PrimaryRegion: Start>}, 
		{'id': 6, 'created_at': datetime.datetime(2017, 9, 5, 20, 42, 35, 7272, tzinfo=<UTC>), 'order': 0, 'path_hash': 'play-demos', 'icon': '', 'background': '/static/backgrounds/squares.png', 'text_colour': 'dark', 'title': 'Play Demos', 'display_title': 'Demos and experiments', 'intro_text': '', 'center_content': False, 'parent_region': <PrimaryRegion: Experiments>}, 
		{'id': 7, 'created_at': datetime.datetime(2017, 9, 17, 9, 21, 2, 363175, tzinfo=<UTC>), 'order': 0, 'path_hash': 'explore-toolkit', 'icon': '', 'background': '/static/backgrounds/squares.png', 'text_colour': 'dark', 'title': 'Explore', 'display_title': 'Explore Toolkit', 'intro_text': '', 'center_content': False, 'parent_region': <PrimaryRegion: Toolkit>}, 
		{'id': 8, 'created_at': datetime.datetime(2017, 11, 3, 17, 30, 49, 175349, tzinfo=<UTC>), 'order': 0, 'path_hash': 'business-experience', 'icon': 'projects', 'background': '/static/backgrounds/triangles.png', 'text_colour': 'light', 'title': 'Business', 'display_title': 'Business Experience', 'intro_text': "So far I've been involved in the development of a range of digital products. This includes a learning platform used by thousands of students and a variety of client projects for a small agency.", 'center_content': False, 'parent_region': <PrimaryRegion: Start>}
	], 
	'content_modules': [
		{'id': 5, 'order': 0, 'module_type': 'demos_menu', 'text': ''}, 
		{'id': 9, 'order': 0, 'module_type': 'text', 'text': "JavaScript was the first area I committed myself to in earnest. My ambition to become a programmer started there. Working in various roles has led me to work with server-side integration too, and my favourite server side technology up to now has been Django, although I've spent as much if not more time with PHP."}, 
		{'id': 10, 'order': 0, 'module_type': 'skills_accordion', 'text': ''}, 
		{'id': 11, 'order': 0, 'module_type': 'text', 'text': 'JavaScript was the first area I committed myself to in earnest. My ambition to become a programmer started there. Working in various roles has led me to work with server-side integration too. On the server side I particularly like Python and Django.<br>\r\n<br>\r\n<br>'}, 
		{'id': 12, 'order': 0, 'module_type': 'skills_accordion', 'text': ''}, 
		{'id': 13, 'order': 0, 'module_type': 'demos_menu', 'text': ''}, 
		{'id': 14, 'order': 0, 'module_type': 'text', 'text': 'I built this application with client-side routing, inspired by the rather interesting <a href="http://www.oregongridiron.com/#!/" target="_blank" rel="noreferrer noopener">Oregon Gridiron</a> Angular application. I have worked to re-create some of the effects with React, Redux and React Router.<br>\r\n<br>\r\n<h3>Interests</h3>\r\nI love learning other languages, including Japanese and Spanish. Before working with technology I was an English teacher abroad, first in in South Korea and later in Spain. I am fascinated by other cultures and times and love to read, travel and imagine. Before teaching my background was Fine Art. I have recently found time to pick up my pencils and brushes again which is a real pleasure. I am also learning some basic piano skills.'}, 
		{'id': 17, 'order': 1, 'module_type': 'text', 'text': '<br>\r\n<h3>INTO University Partnerships</h3>\r\nI worked within an in-house team to deliver a digital learning platform used by thousands of INTO students. I helped to develop the restyle maintaining the company brand and offering an enjoyable user experience. This brought me into professional contact with Django, PHP, ReactJS, CSS and Sass, IDEs PyCharm and PHPStorm, Gulp and Webpack amongst other things.<br>\r\n<br>\r\n<h3>Agency Work</h3>\r\nI currently work in a fast-paced agency environment where we negotiate multiple client accounts within tight time scales. We have improved our workflow through the development of small starter frameworks, saving time spent on common tasks.  I work flexibly on both server-side and client-side tasks producing high-performance websites for a variety of clients.'}
	], 
	'skill_areas': [
		{'id': 2, 'created_at': datetime.datetime(2017, 9, 7, 19, 34, 33, 600688, tzinfo=<UTC>), 'order': 0, 'title': 'JavaScript', 'text': 'A rapidly evolving technology, JavaScript remains a primary interest area for me. When it comes to building UIs I am most intrigued by the functionality (although I also appreciate aesthetics).<br>\r\n<br>\r\nIt\'s an exciting time for JavaScript - not least because of ES6 and its syntax improvements. <a href="https://www.contentful.com/blog/2017/04/04/es6-modules-support-lands-in-browsers-is-it-time-to-rethink-bundling/" target="_blank" rel="noopener noreferrer">Stefan Judis</a> has some interesting thoughts about the future of ES6 in browsers. For now we continue to transpile \'future\' code into universally supported code. <br>\r\n<br>\r\nWorking with JavaScript frameworks and libraries like ReactJS and AngularJS has inspired me to write better \'vanilla\' code. In my current role we developed a set of common UI components without any library dependencies, not even jQuery. I use Webpack for bundling, working modular whether I\'m using React, jQuery or plain JavaScript.<br>\r\n<br>\r\nI enjoy working with ReactJS and used the library along with React Router and Redux to build the data-driven application you\'re now visiting. In September 2016 I facilitated a short workshop on React Router at Codebar\'s <a href="https://medium.com/the-codelog/uncodebar-3-3d879ecd2d7c" target="_blank" rel="noopener noreferrer">Uncodebar 3</a> \'unconference\' event.<br>\r\n<br>\r\nCheck out <a href="/#/experiments/play-demos">experiments</a> to see some of the more playful things I have done with JavaScript.'}, 
		{'id': 5, 'created_at': datetime.datetime(2017, 10, 10, 15, 15, 17, 570359, tzinfo=<UTC>), 'order': 1, 'title': 'UI styling', 'text': "A web developer's career cannot begin before embracing the American spelling of 'colour'. Well, when working with CSS at least.<br>\r\n<br>\r\nOriginally coming to the industry with the ambition to become a 'front-end' developer, I focussed on a three-part skill set: HTML, CSS and JavaScript. Although experience has given me most satisfaction in JavaScript and programming, I considered these areas to be equally important, and have continued to work closely with styling.<br>\r\n<br>\r\nSass affords us many conveniences of programming-inspired syntax, but CSS has its own unique behaviours. For example, from a purely JavaScript point of view, you could shun stylesheets altogether and inline all styles with React components, as some programmers do. I stick with external cascading style sheets - let's not forget how specificity and the cascade work.<br>\r\n<br>\r\nStatic assets aside, if you're working with dynamically computed styles it can be very useful to apply them via React's 'style' attribute."}, 
		{'id': 3, 'created_at': datetime.datetime(2017, 9, 7, 19, 41, 22, 641355, tzinfo=<UTC>), 'order': 2, 'title': 'Server-side integration', 'text': 'My current role involves working within a small team, undertaking a broad variety of tasks. A large part of the work is setting up CMS systems for content editors. This involves channeling a level of control over page structure and appearance we afford to clients.<br>\r\n<br>\r\nI mostly use PHP to build flexible template systems on the back end. These templates take data from the CMS and display content according to mockups from designers. I also use Python/Django which has its own beautiful template system.'}, 
		{'id': 4, 'created_at': datetime.datetime(2017, 10, 10, 11, 30, 45, 665837, tzinfo=<UTC>), 'order': 3, 'title': 'Python', 'text': "The Python programming language remains one of my favourite technologies due to its power and easy-on-the-eye (and mind) syntax. I recently started attending Brighton Python User Group and hope to have more involvement with Python in the future.<br>\r\n<br>\r\nI first came across Python in a previous role working on a learning platform built on Django. I continue to use this framework for my personal projects (the app you're visiting now has a Django API) and will always enjoy working with it."}, 
		{'id': 6, 'created_at': datetime.datetime(2017, 11, 30, 17, 56, 38, 382478, tzinfo=<UTC>), 'order': 5, 'title': 'Tools and Version Control', 'text': 'All the usual tools of the trade are part of my practice. Git, the command line and task runners such as Gulp and Webpack are always close to hand. at INTO University Partnerships I used the IDEs PyCharm and PHPStorm.<br>\r\n<br>\r\nYou can some of my source code on <a href="https://github.com/josephfalconer" target="_blank" rel="noreferrer noopener">Github</a>.'}
	], 
	'navigation_links': [
		{'id': 5, 'order': 0, 'icon': 'logo', 'text': 'Start', 'linked_region': 'start'}, 
		{'id': 2, 'order': 1, 'icon': 'skills', 'text': 'Toolkit', 'linked_region': 'toolkit'}, 
		{'id': 6, 'order': 2, 'icon': 'demos', 'text': 'Experiments', 'linked_region': 'experiments'}
	], 
	'demo_links': [
		{'id': 4, 'created_at': datetime.datetime(2017, 9, 7, 19, 25, 2, 282677, tzinfo=<UTC>), 'order': 0, 'title': 'React Redux Game', 'text': "You must control the cat. Make sure you eat enough, and don't run into the dog. That dog I was talking about chases you by the way!", 'path': 'react-redux-game'}, 
		{'id': 3, 'created_at': datetime.datetime(2017, 9, 7, 19, 24, 38, 44303, tzinfo=<UTC>), 'order': 1, 'title': 'Submarine Parallax Game', 'text': "Navigate the submarine to the ocean floor via a tangle of 3d seaweed. You'll encounter sea creatures who test your knowledge along the way.", 'path': 'submarine-parallax-game'}
	]
}