# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.TextField(),
        ),
    ]
