# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-16 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20170714_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.CharField(choices=[('skills', 'Skills'), ('projects', 'Projects'), ('demos', 'Demos')], default='skills', max_length=20),
            preserve_default=False,
        ),
    ]
