# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='icon',
            field=models.CharField(choices=[('logo', 'Logo'), ('skills', 'Skills'), ('projects', 'Projects'), ('demos', 'Demos')], max_length=20),
        ),
    ]
