# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20170718_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='background',
            field=models.CharField(choices=[('asanoha-400px.png', 'Japanese Asanoha'), ('dark-triangles.png', 'Dark Triangles'), ('sayagata-400px.png', 'Japanese Sayagata'), ('seigaiha.png', 'Seigaiha')], max_length=20),
        ),
    ]
