# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20170718_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='background',
            field=models.CharField(choices=[('asanoha-400px.png', 'Japanese Asanoha'), ('triangles.png', 'Triangles and Hexagons'), ('pyramids.png', 'Pyramids'), ('seigaiha.png', 'Seigaiha')], max_length=20),
        ),
    ]
