# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20170730_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='module_name',
            field=models.CharField(blank=True, choices=[('skills', 'Skills Acordion'), ('demos', 'Demos Menu'), ('projects', 'Projects Menu')], max_length=20),
        ),
    ]
