# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlink',
            name='linked_zone',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
