# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_navigationlink_linked_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='linked_zone',
            field=models.CharField(blank=True, choices=[('start', 'Start'), ('toolkit', 'Toolkit'), ('experiments', 'Experiments')], default=None, max_length=50),
        ),
    ]
