# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-05 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='internal_link_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='internal_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
