# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-05 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170824_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlink',
            name='linked_region',
            field=models.CharField(blank=True, choices=[('', 'Start'), ('skills', 'Skills'), ('demos', 'Demos'), ('projects', 'Projects'), ('test-primary', 'Test Primary')], default=None, max_length=50),
        ),
    ]
