# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='path_hash',
            field=models.CharField(default='Enter path hash', max_length=255),
            preserve_default=False,
        ),
    ]
