# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_path_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='path_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
