# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20170802_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='background',
            field=models.CharField(choices=[('/static/backgrounds/asanoha-400px.png', 'Japanese Asanoha'), ('/static/backgrounds/triangles.png', 'Triangles and Hexagons'), ('/static/backgrounds/pyramids.png', 'Pyramids'), ('/static/backgrounds/seigaiha.png', 'Seigaiha'), ('/static/backgrounds/squares.png', 'Grey and White Squares')], default='Choose', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='icon',
            field=models.CharField(choices=[('logo', 'Logo'), ('skills', 'Skills'), ('projects', 'Projects'), ('demos', 'Demos')], default='Choose', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='intro_text',
            field=models.TextField(default='Enter intro'),
            preserve_default=False,
        ),
    ]
