# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_auto_20170803_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='background',
            field=models.CharField(blank=True, choices=[('/static/backgrounds/asanoha-400px.png', 'Japanese Asanoha'), ('/static/backgrounds/triangles.png', 'Triangles and Hexagons'), ('/static/backgrounds/pyramids.png', 'Pyramids'), ('/static/backgrounds/seigaiha.png', 'Seigaiha'), ('/static/backgrounds/squares.png', 'Grey and White Squares')], max_length=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='icon',
            field=models.CharField(blank=True, choices=[('logo', 'Logo'), ('skills', 'Skills'), ('projects', 'Projects'), ('demos', 'Demos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='region',
            name='intro_text',
            field=models.TextField(blank=True),
        ),
    ]
