# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_auto_20170803_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='icon',
            field=models.CharField(blank=True, choices=[('logo', 'Logo'), ('skills', 'Skills'), ('projects', 'Projects'), ('demos', 'Demos')], max_length=200),
        ),
    ]
