# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_auto_20170803_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='background',
            field=models.CharField(blank=True, choices=[('/static/backgrounds/asanoha-400px.png', 'Japanese Asanoha'), ('/static/backgrounds/triangles.png', 'Triangles and Hexagons'), ('/static/backgrounds/pyramids.png', 'Pyramids'), ('/static/backgrounds/seigaiha.png', 'Seigaiha'), ('/static/backgrounds/squares.png', 'Grey and White Squares')], max_length=200),
        ),
    ]
