# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_auto_20170803_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='icon',
            field=models.CharField(blank=True, choices=[('logo', 'Logo'), ('skills', 'Spanner and Screwdriver'), ('projects', '@ symbol'), ('demos', 'Laboratory Beaker')], max_length=200),
        ),
    ]
