# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0008_auto_20170803_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='short_name',
            field=models.CharField(default='enter name', max_length=20),
            preserve_default=False,
        ),
    ]
