# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0009_auto_20170907_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodule',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
