# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0010_contentmodule_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmodule',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.SubRegion', to_field=b'path_hash'),
        ),
        migrations.AlterField(
            model_name='primaryregion',
            name='path_hash',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='primaryregion',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='parent_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.PrimaryRegion', to_field=b'path_hash'),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='path_hash',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subregion',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
