# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0010_auto_20170807_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('text', 'Text'), ('skills_accordion', 'Skills Accordion'), ('demos_menu', 'Demos Menu')], max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.Region')),
            ],
        ),
    ]
