# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-08 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0011_contentmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodule',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
