# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0012_contentmodule_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentmodule',
            options={'ordering': ['order']},
        ),
    ]
