# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0014_region_text_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRegion',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regions.Region')),
            ],
            bases=('regions.region',),
        ),
        migrations.CreateModel(
            name='PrimaryRegion',
            fields=[
                ('region_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='regions.Region')),
            ],
            bases=('regions.region',),
        ),
    ]
