# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0015_childregion_primaryregion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='long_title',
            new_name='display_title',
        ),
    ]
