# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='SkillArea',
        ),
    ]
