# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-16 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20181123_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationlink',
            name='linked_page',
        ),
        migrations.DeleteModel(
            name='NavigationLink',
        ),
    ]
