# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-26 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('path_hash', models.CharField(blank=True, max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, choices=[('LOGO', 'Logo'), ('TOOLS', 'Spanner and Screwdriver'), ('PROJECTS', '@ symbol'), ('DEMOS', 'Laboratory Beaker')], max_length=200)),
                ('background', models.CharField(blank=True, choices=[('/static/backgrounds/asanoha-400px.png', 'Japanese Asanoha'), ('/static/backgrounds/triangles.png', 'Triangles and Hexagons'), ('/static/backgrounds/pyramids.png', 'Pyramids'), ('/static/backgrounds/seigaiha.png', 'Seigaiha'), ('/static/backgrounds/squares.png', 'Grey and White Squares')], max_length=200)),
                ('text_colour', models.CharField(choices=[('light', 'Light Text'), ('dark', 'Dark Text')], default='dark', max_length=200)),
                ('title', models.CharField(max_length=20)),
                ('display_title', models.CharField(blank=True, max_length=255)),
                ('intro_text', models.TextField(blank=True)),
                ('center_content', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('module_type', models.CharField(choices=[('TEXT', 'Text'), ('SKILLS_ACCORDION', 'Skills Accordion'), ('DEMOS_MENU', 'Demos Menu')], max_length=100)),
                ('text', models.TextField(blank=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.ChildZone', to_field='path_hash')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ParentZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(default=0)),
                ('path_hash', models.CharField(blank=True, max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, choices=[('LOGO', 'Logo'), ('TOOLS', 'Spanner and Screwdriver'), ('PROJECTS', '@ symbol'), ('DEMOS', 'Laboratory Beaker')], max_length=200)),
                ('background', models.CharField(blank=True, choices=[('/static/backgrounds/asanoha-400px.png', 'Japanese Asanoha'), ('/static/backgrounds/triangles.png', 'Triangles and Hexagons'), ('/static/backgrounds/pyramids.png', 'Pyramids'), ('/static/backgrounds/seigaiha.png', 'Seigaiha'), ('/static/backgrounds/squares.png', 'Grey and White Squares')], max_length=200)),
                ('text_colour', models.CharField(choices=[('light', 'Light Text'), ('dark', 'Dark Text')], default='dark', max_length=200)),
                ('title', models.CharField(max_length=20)),
                ('display_title', models.CharField(blank=True, max_length=255)),
                ('intro_text', models.TextField(blank=True)),
                ('center_content', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='childzone',
            name='parent_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zones.ParentZone', to_field='path_hash'),
        ),
    ]
