# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-01 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0004_auto_20180227_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childzone',
            name='parent_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_zones', to='zones.ParentZone'),
        ),
        migrations.AlterField(
            model_name='contentmodule',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_modules', to='zones.ChildZone'),
        ),
    ]
